# Site settings
title: Dom Meets Web
smalltalk: "On the Path to Becomming A Full-Stack Developer"
description: > # Dominic Smith's blog on his journey towards becomming a full-stack Jedi
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
url: "" # the base hostname & protocol for your site
twitter_username: 415domsmith
github_username:  
facebook_username: 
portfolio_url: http://415domsmith.github.io/doms_portfolio/

# Build settings
markdown: kramdown
